version: '2'
services:
    interhyp4hackathon-app:
        image: interhyp4hackathon
        environment:
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_DATASOURCE_URL=jdbc:postgresql://interhyp4hackathon-postgresql:5432/interhyp4hackathon
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
        ports:
            - 8080:8080
    interhyp4hackathon-postgresql:
        extends:
            file: postgresql.yml
            service: interhyp4hackathon-postgresql
